import { getErrorMessage } from '../utils/errorHelpers';
import { getSecure, setSecure, removeSecure } from '../services/secureStorage';

const DEFAULT_BRIDGE_PORT = 30085;
let detectedBridgePort: number | null = null;

export function resetBridgePort(): void {
  detectedBridgePort = null;
  console.log('[API] Bridge port cache cleared');
}

export async function detectBridgePort(): Promise<number> {
  if (detectedBridgePort) return detectedBridgePort;
  console.log('[API] Starting Bridge port detection...');
  for (let attempt = 0; attempt < 6; attempt++) {
    for (let port = DEFAULT_BRIDGE_PORT; port < DEFAULT_BRIDGE_PORT + 10; port++) {
      try {
        const res = await fetch(`http://127.0.0.1:${port}/api/system-status`, { signal: AbortSignal.timeout(3000) });
        if (res.ok) {
          detectedBridgePort = port;
          console.log(`[API] Bridge found on port ${port} (attempt ${attempt + 1})`);
          return port;
        }
      } catch {}
    }
    if (attempt < 5) {
      const delay = attempt < 2 ? 1500 : 2000;
      console.log(`[API] Bridge not found on attempt ${attempt + 1}, retrying in ${delay}ms...`);
      await new Promise(r => setTimeout(r, delay));
    }
  }
  console.log(`[API] Bridge detection failed after 6 attempts. Using default port ${DEFAULT_BRIDGE_PORT}`);
  return DEFAULT_BRIDGE_PORT;
}

function getApiBase(): string {
  if (detectedBridgePort && detectedBridgePort !== DEFAULT_BRIDGE_PORT) {
    return `http://127.0.0.1:${detectedBridgePort}/api`;
  }
  return `http://127.0.0.1:${DEFAULT_BRIDGE_PORT}/api`;
}

export let API_BASE = `http://127.0.0.1:${DEFAULT_BRIDGE_PORT}/api`;
export const GATEWAY_BASE = 'http://127.0.0.1:30090';
export const CHENGDU_API = 'http://127.0.0.1:30090/api';
export const isTauriApp = typeof window !== 'undefined' && !!(window as any).__TAURI_INTERNALS__;

let apiReady: Promise<void> | null = null;

async function ensureBridgeToken() {
  if (isTauriApp) {
    try {
      const { invoke } = await import('@tauri-apps/api/core');
      const key: string = await invoke('get_bridge_api_key');
      if (key) {
        localStorage.setItem('bridge_api_key', key);
      }
    } catch (e) {
      console.warn('[API] Failed to get bridge API key:', e);
    }
  }
}

if (isTauriApp) {
  apiReady = (async () => {
    const port = await detectBridgePort();
    API_BASE = `http://127.0.0.1:${port}/api`;
    detectedBridgePort = port;
    await ensureBridgeToken();
    console.log('[API] Bridge ready - port:', port);
  })();
}

export async function waitForApiReady(): Promise<void> {
  if (apiReady) await apiReady;
}

let nativeEngineInitialized = false;

async function ensureNativeEngine() {
  if (isTauriApp && !nativeEngineInitialized) {
    try {
      const { nativeEngineAPI } = await import('../utils/tauriAPI');
      await nativeEngineAPI.init();
      nativeEngineInitialized = true;
    } catch (e) {
      console.warn('[API] Failed to initialize native engine:', e);
    }
  }
}

// Local bridge API token (generated by Rust bridge at startup).
// Falls back to auth_token for backward compatibility.
export function getToken() {
  return localStorage.getItem('bridge_api_key') || localStorage.getItem('auth_token');
}

// Resolve effective user_mode for a given conversation.
export function getUserModeForConversation(conversationId?: string): string {
  if (conversationId) {
    try {
      const raw = localStorage.getItem('cross_mode_overrides');
      if (raw) {
        const map = JSON.parse(raw);
        if (map && typeof map === 'object' && !Array.isArray(map) && map[conversationId]) {
          return map[conversationId];
        }
      }
    } catch (e) {
      console.warn('[API] Failed to parse cross_mode_overrides, using default mode');
    }
  }
  return localStorage.getItem('user_mode') || 'clawparrot';
}

// Secure credential cache (populated async on app init)
export let _cachedApiKey: string | null = null;
export let _cachedCustomApiKey: string | null = null;

export function setCachedCredentials(apiKey: string | null, customApiKey: string | null) {
  _cachedApiKey = apiKey;
  _cachedCustomApiKey = customApiKey;
}

export async function preloadSecureCredentials() {
  try {
    _cachedApiKey = await getSecure('ANTHROPIC_API_KEY');
    _cachedCustomApiKey = await getSecure('CUSTOM_API_KEY');
  } catch (e) {
    console.warn('[API] Failed to preload secure credentials:', e);
  }
}

// Resolve env_token / env_base_url to send to bridge.
export function resolveEnvCreds(mode: string): { env_token?: string; env_base_url?: string } {
  const secureApiKey = _cachedApiKey || localStorage.getItem('ANTHROPIC_API_KEY');
  const secureCustomKey = _cachedCustomApiKey || localStorage.getItem('CUSTOM_API_KEY');

  if (mode === 'clawparrot') {
    return {
      env_token: secureApiKey || undefined,
      env_base_url: localStorage.getItem('ANTHROPIC_BASE_URL') || undefined,
    };
  }
  return {
    env_token: secureCustomKey || secureApiKey || undefined,
    env_base_url: localStorage.getItem('CUSTOM_BASE_URL') || localStorage.getItem('ANTHROPIC_BASE_URL') || undefined,
  };
}

// 路由到后端网关的路径前缀（这些路由在 Chengdu gateway 上，不在 bridge 上）
export const GATEWAY_ROUTES = [
  '/auth/', '/user/', '/payment/', '/redemption/',
  '/github/', '/artifacts/', '/code/', '/multiagent/',
  '/conversations/export', '/conversations/sso',
];

function isGatewayRoute(path: string): boolean {
  return GATEWAY_ROUTES.some(prefix => path.startsWith(prefix));
}

// 通用请求方法
export async function request(path: string, options: RequestInit = {}) {
  await waitForApiReady();
  const token = getToken();
  const headers: HeadersInit = {
    'Content-Type': 'application/json',
    ...(options.headers || {}),
  };
  if (token) {
    (headers as any)['Authorization'] = `Bearer ${token}`;
  }
  const base = isGatewayRoute(path) ? CHENGDU_API : API_BASE;
  const res = await fetch(`${base}${path}`, { ...options, headers });
  if (res.status === 401) {
    localStorage.removeItem('auth_token');
    localStorage.removeItem('user');
    window.location.hash = '#/login'; window.location.reload();
    throw new Error('认证失效');
  }
  if (!res.ok) {
    const errorData = await res.json().catch(() => ({}));
    throw new Error(errorData.error || `Request failed: ${res.status}`);
  }
  return res;
}

// 系统状态（检测 git-bash 等运行时依赖）
export async function getSystemStatus(): Promise<{
  platform: string;
  gitBash: { required: boolean; found: boolean; path: string | null };
}> {
  const res = await fetch(`${API_BASE}/system-status`);
  if (!res.ok) throw new Error('Failed to get system status');
  return res.json();
}

export async function healthCheck(): Promise<boolean> {
  try {
    const res = await fetch(`${API_BASE}/system-status`, { signal: AbortSignal.timeout(5000) });
    return res.ok;
  } catch {
    return false;
  }
}

let bridgeReachableCache: boolean | null = null;

export async function isBridgeReachable(): Promise<boolean> {
  if (bridgeReachableCache !== null) return bridgeReachableCache;
  try {
    const port = await detectBridgePort();
    const res = await fetch(`http://127.0.0.1:${port}/api/system-status`, { signal: AbortSignal.timeout(2000) });
    bridgeReachableCache = res.ok;
  } catch {
    bridgeReachableCache = false;
  }
  return bridgeReachableCache;
}

export function resetBridgeReachableCache(): void {
  bridgeReachableCache = null;
}

// Check if user is logged in via gateway
export async function isGatewayLoggedIn(): Promise<boolean> {
  const key = _cachedApiKey || localStorage.getItem('ANTHROPIC_API_KEY');
  const user = await getSecure('gateway_user') || localStorage.getItem('gateway_user');
  return !!(key && user);
}

// Gateway logout
export async function gatewayLogout() {
  await removeSecure('ANTHROPIC_API_KEY');
  localStorage.removeItem('ANTHROPIC_BASE_URL');
  await removeSecure('gateway_user');
  localStorage.removeItem('gateway_quota');
  await removeSecure('auth_token');
  localStorage.removeItem('user');
  _cachedApiKey = null;
  _cachedCustomApiKey = null;
}

// Get gateway usage status
export async function getGatewayUsage() {
  const key = _cachedApiKey || localStorage.getItem('ANTHROPIC_API_KEY');
  if (!key) return null;
  const res = await fetch(`${GATEWAY_BASE}/gateway/usage`, {
    headers: { 'x-api-key': key },
  });
  if (!res.ok) return null;
  return res.json();
}

export { ensureNativeEngine };
